service: invpc

package:
  individually: true
  exclude:
    - venv/**
    - .git/**
    - node_modules/**
    - .serverless/**
    - .vscode/**
    - src/venv/**
    
provider:
  name: aws
  region: ap-southeast-1
  runtime: python3.6
  stage: latest
  versionFunctions: false
  deploymentBucket:
    name: cdktoolkit-stagingbucket-tn88ytsk4d6y
  tags:
    project: '${self:service}.${self:provider.stage}'
  environment:
    ALB: 'http://ip-10-0-202-243.ap-southeast-1.compute.internal:5000'
  

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  helloWorldInside:
    handler: hello_world_inside.main
    module: src
    name: '${self:service}-helloWorldInside'
    # vpc:
    #   securityGroupIds:
    #     - 
    #       'Fn::ImportValue': 'LambdaInVpcSecurityGroupId'
    #   subnetIds:
    #     - 
    #       'Fn::ImportValue': 'PrivateSubnetId0'
    #     - 
    #       'Fn::ImportValue': 'PrivateSubnetId1'
    vpc:
      securityGroupIds:
        - sg-0991489e4b5285ede
      subnetIds:
        - subnet-0254e6e24dbd57b89
        - subnet-0e76d4d0b6f252228
    events:
      - http: 
          path: '/helloInside'
          method: get
  helloWorldOutside:
    handler: hello_world_outside.main
    module: src
    name: '${self:service}-helloWorldOutside'
    events:
      - http: 
          path: '/helloOutside'
          method: get